### ISSUE TITLE
Support for non 16:9 Aspect Ration

### ISSUE THREAD

**Issue by marcoSchr** [opensuspect/opensuspect-legacy#109]
Currently the game is forced to 16:9 by black bars, either on top and bottom or left and right.
It would be good to support more aspect ratios.

**Comment by monban** [comment]
I agree that this is something we should do, however I don't think it's required for the Alpha, so I'm going to assign this to the Beta milestone.

**Comment by TheRyeGuyWhoWillNowDie** [comment]
I guess this is fixed now as of pr #111

**Comment by marcoSchr** [comment]
This is fixed now. It works as expected. 
I have tested this in the lobby with the limited vision and in game.
