### ISSUE TITLE
UI doesn't adapt to different screen sizes

### ISSUE THREAD

**Issue by darshadi** [opensuspect/opensuspect-legacy#110]
Changed the screen resolution to 1920x1080 and since many of the ui nodes aren't properly set to centered/full rect/under a center container etc many things are moved to either off screen or to the side whenever screen resolution isn't 1024x600. This will become a big issue in the future if it isn't taken care of soon.

**Comment by TheSecondReal0** [comment]
All existing UI has been updated to scale correctly in #112
