### ISSUE TITLE
The server accepts new players after the user pressed "Start game"

### ISSUE THREAD

**Issue by nicemicro** [opensuspect/opensuspect-legacy#129]
I have "version = 5" under testing, after commit 769f394.
I tested with three instances running.

First instance starts a game as server.
Second instance joins the game.
I press "start game" on the server instance. The red dummy character appears on the screen, the "Lobby" text disappears.
Third instance joins the game.

The three players see each other, but while the first two instances have the red dummy character on screen, the third one sees the "Lobby" text.

**Comment by monban** [comment]
Got this one.
