### ISSUE TITLE
Update README and CONTRIBUTORS

### ISSUE THREAD

**Issue by moxvallix** [opensuspect/opensuspect-legacy#132]
README.md and CONTRIBUTORS.txt are outdated, and could do with an update to better match the current state of the project. Updating the list of contributors by maybe putting names, then the teams they are active in might be a good idea. README.md could link to the website, nextcloud etc. Maybe it is also time to remove "Placey" the placeholder alien.

**Comment by nicemicro** [comment]
I wholeheartedly agree. I'll propose the changes in a PR, and I'll let others evaluate it.
