### ISSUE TITLE
Appearance selection, BASIC

### ISSUE THREAD

**Issue by monban** [opensuspect/opensuspect-legacy#159]
Allow players to choose their appearance while in the lobby.

Initially implement as a button with a popup. For this basic version, we're more interested in implementing the plumbing. Allow the player to select an arbitrary color from a chooser, and save that to a place that will be persisted between scenes.

Later on we will receive input from the Game Design team as to a more interesting system (disguise kit? wardrobe interaction? opening your own dossier and "correcting" it?)

**Comment by Poket-Jony** [comment]
If this feature is required in the future you can merge https://github.com/opensuspect/opensuspect/pull/204

**Comment by nicemicro** [comment]
> If this feature is required in the future you can merge #204

We have finally included the prototype of the character models we plan to use in the game, if you are still interested in the issue, we'll need a function to change the skin color (but not the clothes).
