### ISSUE TITLE
Player entry point entity

### ISSUE THREAD

**Issue by monban** [opensuspect/opensuspect-legacy#161]
Create a new type of Node that can be placed into a scene. For the purposes of this spec, we will call it 'Player Spawn'. Upon entering the Main Game mode, the server will assign each player to an unoccupied Player Spawn, at random. That location will be used for the initial position of their character.

**Comment by vainiovano** [comment]
I don't understand enough Godot to do this

**Comment by vincens2005** [comment]
done. PR #169 [https://github.com/opensuspect/opensuspect/pull/169](
https://github.com/opensuspect/opensuspect/pull/169)

**Comment by TheSecondReal0** [comment]
While #169 adds a player spawn node, there is currently no way to have multiple spawn points

**Comment by vainiovano** [comment]
Why was this closed? While #169 adds a player spawn node, it doesn't implement the system that's described here.
