### ISSUE TITLE
Very basic map

### ISSUE THREAD

**Issue by monban** [opensuspect/opensuspect-legacy#162]
Acceptance criteria
- Two rooms
- Player spawn points (#161 prerequisite)
- Some kind of texture on the walls and floors (programmer temporary art is okay)

Non-goals
- Any type of actual map design
- Looks good
- Any kind of mechanics

**Comment by BrianGaucher** [comment]
Just a suggestion, having a button which makes workers win, could be helpful for testing the win mechanics. Just simple buttons, no task.
