### ISSUE TITLE
Lighting: people who are outside the light radius are still visible

### ISSUE THREAD

**Issue by nicemicro** [opensuspect/opensuspect-legacy#164]
While the environment gets the dark overlay, the characters are still visible outside the light radius, including the names.

**Comment by vainiovano** [comment]
First bad commit is 883a8aa85e912df8551b28b217b9c67bc7f96a6e

**Comment by vainiovano** [comment]
Caused by these lines

https://github.com/opensuspect/opensuspect/blob/81060f616d50c524d58e9faa546485dbf6bb9780/src/assets/player/player.gd#L23-L28
