### ISSUE TITLE
Kill mechanics for infiltrators

### ISSUE THREAD

**Issue by moxvallix** [opensuspect/opensuspect-legacy#193]
A kill mechanic for players assigned as an "infiltrator". Used to kill others not assigned infiltrator.

Should have:
- Reloading (triggered by player, has a cool-down time)
- Adjustable range
- A shortcut, and a GUI icon
- Toggle-able based on other events

See https://github.com/opensuspect/design-document/blob/main/general_gameplay.md.

**Comment by jngo102** [comment]
I think I'll give this a shot, though I won't know how to draw the icon until the art style is finalized.
