### ISSUE TITLE
UI exits game, takes back to menu screen

### ISSUE THREAD

**Issue by moxvallix** [opensuspect/opensuspect-legacy#227]
Woo, this is my first bug report!

Description of Bug:
Pressing exit from the keybinds menu whilst in a game, takes the player back to the menu screen, rather than back to the game.

Steps to reproduce:
1. Host a game
2. Open the menu, go Settings > Keybinds
3. Press the back button

**Comment by TheRyeGuyWhoWillNowDie** [comment]
this was fixed
