### ISSUE TITLE
Change variable names and comments to be used uniformly: agents and infiltrators

### ISSUE THREAD

**Issue by nicemicro** [opensuspect/opensuspect-legacy#249]
Throughout the code, we use different names for the "teams" or "roles" the players get.

Based on the game design team's decision, the larger team, the default role should be called "agent" / "agents", while all smaller teams, who try to disrupt the main team's work should be called "infiltrator" / "infiltrators".

The variable names and comments throughout the codebase should reflect this for clarity.

**Comment by vincens2005** [comment]
I'm going to work on this this week, it shouldn't be too hard, just a lot of grep
