### ISSUE TITLE
Clean up main.gd

### ISSUE THREAD

**Issue by TheSecondReal0** [opensuspect/opensuspect-legacy#256]
## Problem
Right now, main.gd is a couple hundred lines long and is responsible for a ton of completely different things at once. It's handling network sync for movement, player appearance, and soon it will also handle it for items. This is on top of handling player spawning and killing.

## Solution(s)
1. Break main.gd apart into multiple scripts, attached to nodes in main.tscn. These specific scripts/nodes would handle their respective tasks. One script would sync appearance, another would sync movement, another items, etc..

If you can think of another solution, please post a comment!

**Comment by TheRyeGuyWhoWillNowDie** [comment]
well i mean that's why it's called main lol

**Comment by nicemicro** [comment]
The appearance handler should provide a way to store player appearance persistently between rounds outside the player instances.
