### ISSUE TITLE
Some form of filtering used while scaling pixelart assets

### ISSUE THREAD

**Issue by MGThePro** [opensuspect/opensuspect-legacy#27]
While it was already visible by default, with #26 it becomes really apparent that some sort of filtering (I assume bilinear filtering) is being used on the assets. I'm not yet familiar enough with godot to figure out if or where a setting is to set it to integer scaling.

**Comment by GrbavaCigla** [comment]
`.import` files are responsible for that. You can find that in the godot docs: https://docs.godotengine.org/en/stable/getting_started/workflow/assets/importing_images.html

**Comment by GrbavaCigla** [comment]
`flags/filter=true` and `compress/lossy_quality=0.7` are set in .import file.
