### ISSUE TITLE
Role screen crashes game on second created game

### ISSUE THREAD

**Issue by nicemicro** [opensuspect/opensuspect-legacy#271]
Way to reproduce:
1. Create a new game
2. Start the game
3. Go back to lobby
4. Go back to main menu
5. Create a new game
6. Start the game

Game crashes with error: Attempt to call function 'set_movement_disabled' in base 'null instance' on a null instance.
Where it occures: 
```
func _clean_up():
	for id in PlayerManager.players:
		PlayerManager.players[id].set_movement_disabled(false)
```
the PlayerManager.players is a dictionary with one element that is NULL

**Comment by TheSecondReal0** [comment]
This bug highlights 2 things:
1. There isn't really any cleanup when the game returns to the main menu (names, roles, players dict, and other stuff like that should be cleared)
2. The role announcement screen doesn't seem to go through the UI system and instead uses a workaround to stop players from moving (shown in the code snippet provided by @nicemicro)

Cleanup should probably have its own issue, while fixing this bug should include adapting role announcement to use the UI system.
