### ISSUE TITLE
Case mixing in directory structure

### ISSUE THREAD

**Issue by tooManyArguments** [opensuspect/opensuspect-legacy#52]
As it is now we are mixing cases in files and directories.
My suggestion is to change it to all lower case, before we have all sorts of standards.
example: /src/Assets should be /src/assets
src/Scenes/UI/PlayGame.tscn becomes src/scenes/ui/playgame.tscn

This would not apply to md's/txt's etc in root directory.

**Comment by moxvallix** [comment]
Sounds like a good idea. If the programming team is happy with all lowercase, could someone make a PR to fix this.

**Comment by tooManyArguments** [comment]
This was solved by PR https://github.com/opensuspect/opensuspect/pull/69 from darshadi, closing.
