### ISSUE TITLE
Fix weird scaling in main.tscn

### ISSUE THREAD

**Issue by TheSecondReal0** [opensuspect/opensuspect-legacy#85]
Right now, the root node of main.tscn is scaled by a factor of .05. I think this is because the textures are so big that they would take up the entire screen if they weren't massively scaled down, but this is a poor solution. We need to decide on standards for image size and/or move a similar solution elsewhere, maybe by scaling down the actual Sprite node instead the entire scene.

**Comment by tooManyArguments** [comment]
Adding assigness from desgin / art team
