### ISSUE TITLE
Proper UI System

### ISSUE THREAD

**Issue by TheSecondReal0** [opensuspect/opensuspect-legacy#99]
Currently, the only ingame UI is made up of a few nodes in main.tscn. We're going to need a much more robust system than that. I think the system needs:
- A heavy focus on modularity (easily add new UI components to manage)
- Easy for other systems to hook into to tell it to show a UI component
- Keep track of whether or not a menu is open

I think a working pause menu from which you can return to the main menu, access settings, and close the game that uses this framework would close this issue.

**Comment by GrbavaCigla** [comment]
Something like how settings system is done?
